### ISSUE TITLE
u-boot build issue

### ISSUE THREAD

**Issue by JohnnyOpcode** [TechNexion/u-boot-edm#3]
HEAD is now at a44a45f... TechNexion: pico-imx6: add PICO-IMX6 board support

user@ubuntu:~/GitHub/u-boot-edm$  make pico-imx6ul_defconfig
#
# configuration written to .config
#
user@ubuntu:~/GitHub/u-boot-edm$ make -j 4
scripts/kconfig/conf  --silentoldconfig Kconfig
  CHK     include/config.h
  UPD     include/config.h
  CFG     u-boot.cfg
  GEN     include/autoconf.mk.dep
In file included from ./include/common.h:21:0:
include/config.h:7:22: fatal error: configs/.h: No such file or directory
compilation terminated.
In file included from ./include/common.h:21:0:
include/config.h:7:22: fatal error: configs/.h: No such file or directory
compilation terminated.
make[1]: *** [include/autoconf.mk.dep] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [u-boot.cfg] Error 1
make: *** No rule to make target `include/config/auto.conf', needed by `include/config/uboot.release'.  Stop.

**Comment by richard-hu** [comment]
Hello, JohnnyOpcode:

We have not yet finished the porting task of all TechNexion products on u-boot 2017.10.
The existing deconfig file for pico-imx6ul is done by NXP for android things.

Moreover, there are two different types of PICO-IMX6UL SOM with 256MB and 512MB DRAM.
The u-boot done by NXP doesn't support SPL (secondary program loader).
So it'd be required to select the corresponding DCD table for different DRAM size of PICO-IMX6UL SOM.
SPL detects the DRAM size and have two different kinds of  DRAM initialization in TechNexion u-boot.
It guarantees the same u-boot binary works on varieties of PICO-IMX6UL SOMs.
  
Could you use TechNexion u-boot 2016.03 in this stage?

I am sorry for the inconvenience to you.
I promise we'll make it ASAP.

BR,

Richard

**Comment by JohnnyOpcode** [comment]
Okay. I will work with 2016.03 for now and watch as 2017.x evolves. Thank-you for the update.

John

**Comment by SleepyDeb** [comment]
@richard-hu hi, i'm booting a pico-imx6ul using the last version of u-boot, everything is fine, but i need to patch DCD definition to match 512mb memory size, can you provvide the DCD constant changes? 
thanks you in advance

### board/technexion/pico-imx6ul/imximage.cfg :
`/*
 * Device Configuration Data (DCD)
 *
 * Each entry must have the format:
 * Addr-type           Address        Value
 *
 * where:
 *	Addr-type register length (1,2 or 4 bytes)
 *	Address	  absolute address of the register
 *	value	  value to be stored in the register
 */

/* Enable all clocks */
DATA 4 0x020c4068 0xffffffff
DATA 4 0x020c406c 0xffffffff
DATA 4 0x020c4070 0xffffffff
DATA 4 0x020c4074 0xffffffff
DATA 4 0x020c4078 0xffffffff
DATA 4 0x020c407c 0xffffffff
DATA 4 0x020c4080 0xffffffff

DATA 4 0x020E04B4 0x000C0000
DATA 4 0x020E04AC 0x00000000
DATA 4 0x020E027C 0x00000030
DATA 4 0x020E0250 0x00000030
DATA 4 0x020E024C 0x00000030
DATA 4 0x020E0490 0x00000030
DATA 4 0x020E0288 0x00000030
DATA 4 0x020E0270 0x00000000
DATA 4 0x020E0260 0x00000030
DATA 4 0x020E0264 0x00000030
DATA 4 0x020E04A0 0x00000030
DATA 4 0x020E0494 0x00020000
DATA 4 0x020E0280 0x00000030
DATA 4 0x020E0284 0x00000030
DATA 4 0x020E04B0 0x00020000
DATA 4 0x020E0498 0x00000030
DATA 4 0x020E04A4 0x00000030
DATA 4 0x020E0244 0x00000030
DATA 4 0x020E0248 0x00000030
DATA 4 0x021B001C 0x00008000
DATA 4 0x021B0800 0xA1390003
DATA 4 0x021B080C 0x00000000
DATA 4 0x021B083C 0x01380134
DATA 4 0x021B0848 0x40404244
DATA 4 0x021B0850 0x40405050
DATA 4 0x021B081C 0x33333333
DATA 4 0x021B0820 0x33333333
DATA 4 0x021B082C 0xf3333333
DATA 4 0x021B0830 0xf3333333
DATA 4 0x021B08C0 0x00921012
DATA 4 0x021B08b8 0x00000800
DATA 4 0x021B0004 0x0002002D
DATA 4 0x021B0008 0x00333030
DATA 4 0x021B000C 0x676B52F3
DATA 4 0x021B0010 0xB66D8B63
DATA 4 0x021B0014 0x01FF00DB
DATA 4 0x021B0018 0x00201740
DATA 4 0x021B001C 0x00008000
DATA 4 0x021B002C 0x000026D2
DATA 4 0x021B0030 0x006B1023
DATA 4 0x021B0040 0x00000047
DATA 4 0x021B0000 0x83180000
DATA 4 0x021B001C 0x02008032
DATA 4 0x021B001C 0x00008033
DATA 4 0x021B001C 0x00048031
DATA 4 0x021B001C 0x15208030
DATA 4 0x021B001C 0x04008040
DATA 4 0x021B0020 0x00000800
DATA 4 0x021B0818 0x00000227
DATA 4 0x021B0004 0x0002552D
DATA 4 0x021B0404 0x00011006
DATA 4 0x021B001C 0x00000000
`

**Comment by TechNexion** [comment]
Hello, SleepyDeb:

We change to initialize DDR in SPL for a long time.
In order to be compatible with both 256/512MB DDR, and i'd suggest to use SPL u-boot.
The attachment is the DCD table for 512MB that i extract from old commit on git and apply the updated DQS read/write calibration parameters from SPL.
It should work well. :)
 
[imximage_512MB.zip](https://github.com/TechNexion/u-boot-edm/files/2262155/imximage_512MB.zip)

**Comment by richard-hu** [comment]
Hello, SleepyDeb:

We change to initialize DDR in SPL for a long time.
In order to be compatible with both 256/512MB DDR, and i'd suggest to use SPL u-boot.
The attachment is the DCD table for 512MB that i extract from old commit on git and apply the updated DQS read/write calibration parameters from SPL.
[imximage_512MB.zip](https://github.com/TechNexion/u-boot-edm/files/2262212/imximage_512MB.zip)

It should work well. :)


BR,

Richard

**Comment by SleepyDeb** [comment]
it works fine thanks!
